spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poi_test?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.fycstart.entity
  configuration:
    mapUnderscoreToCamelCase: true
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config.id-type: auto